//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoMaintenace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public string VideoId { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public int Download { get; set; }
        public string GenreId { get; set; }
    
        public virtual Genre Genre { get; set; }

        public decimal CalculateFee()
        {
            return Convert.ToDecimal(Download) * Price * 0.15m;
            
        }
    }
}
